#if UNITY_EDITOR
using UnityEditor;
using System.IO;

public static class BuildScript {
    [MenuItem("Tools/ClubBlackout/Build Android APK")]
    public static void BuildAndroidAPK() {
        // Ensure scenes exist (generated by SceneSetupTool)
        string[] scenes = new string[] {
            "Assets/Scenes/MainMenu.unity",
            "Assets/Scenes/GameSetup.unity",
            "Assets/Scenes/Game.unity"
        };

        // Output path
        var outputDir = "Builds/Android";
        var outputPath = Path.Combine(outputDir, "ClubBlackout.apk");
        if (!Directory.Exists(outputDir)) Directory.CreateDirectory(outputDir);

        // Switch platform to Android
        EditorUserBuildSettings.SwitchActiveBuildTarget(BuildTargetGroup.Android, BuildTarget.Android);
        EditorUserBuildSettings.buildAppBundle = false; // build APK, not AAB

        var report = BuildPipeline.BuildPlayer(scenes, outputPath, BuildTarget.Android, BuildOptions.None);
        if (report.summary.result == UnityEditor.Build.Reporting.BuildResult.Succeeded) {
            EditorUtility.DisplayDialog("Build", "Android APK built successfully:\n" + outputPath, "OK");
        } else {
            EditorUtility.DisplayDialog("Build", "Build failed: " + report.summary.result, "OK");
        }
    }
}
#endif